{{- $kind := lower .Values.app.kind -}}
{{- if and .Values.autoscaling.enabled (ne $kind "daemonset") -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if eq $kind "deployment"  }}
    kind: Deployment
    {{- else if eq $kind "statefulset"  }}
    kind: StatefulSet
    {{- else }}
    {{- fail (printf "unknow kind %s" $kind) }}
    {{- end }}
    name: {{ include "generic.fullname" . }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
{{- end -}}
