{{- if .Values.httpProxy.enabled -}}
{{- $fullName := include "generic.fullname" . -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.httpProxy.annotations | nindent 4 }}
spec:
  virtualhost:
    fqdn: {{ .Values.httpProxy.host }}
    {{- with .Values.httpProxy.tls }}
    tls:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.httpProxy.corsPolicy }}
    corsPolicy:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.httpProxy.rateLimitPolicy }}
    rateLimitPolicy:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  routes:
    {{- range .Values.httpProxy.routes }}
    - conditions:
      - prefix: {{ .prefix }}
      services:
        - name: {{ $fullName }}
          port: {{ .port }}
    {{- end }}
{{- end }}
