{{ range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "generic.fullname" $) .name }}
  labels:
    {{- include "generic.labels" $ | nindent 4 }}
{{- with .data }}
data:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- with .stringData }}
stringData:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{ end }}
