image:
  repository: hub.teko.vn/data/spark
  tag: 2.4.4-hadoop-3.2.1
  pullPolicy: IfNotPresent

app:
  replicas: 1
  command:
    - spark
    - history-server

  ## initContainers configs
  initContainers:
    - name: init
      image: app/init:1.0
      args: [run, init]

  ## sidecarContainers configs
  sidecarContainers:
    - name: sidecar
      image: app/sidecar:1.0
      args: [run, sidecar]
